import { NextResponse } from "next/server";
import { PDFDocument, StandardFonts, rgb } from "pdf-lib";
import { createAdminClient } from "@/lib/supabase/admin";
import { getCurrentStudioContext } from "@/lib/auth/studio";

function line(page: any, font: any, label: string, value: string, y: number) { page.drawText(label, { x: 54, y, size: 10, font, color: rgb(.35,.35,.42) }); page.drawText(value || "—", { x: 180, y, size: 10, font, color: rgb(.08,.08,.12), maxWidth: 360 }); }
export async function GET(_request: Request, { params }: { params: Promise<{ envelopeId: string }> }) {
  const { envelopeId } = await params; const context = await getCurrentStudioContext(); const admin = createAdminClient();
  const { data: envelope } = await admin.from("document_sign_envelopes").select("id,title,status,signer_name,signer_email,source_sha256,signed_sha256,sent_at,viewed_at,started_at,completed_at,signature_method,signed_timezone,consent_text").eq("id", envelopeId).eq("studio_id", context.studioId).maybeSingle();
  if (!envelope || envelope.status !== "completed") return new NextResponse("Certificate unavailable", { status: 404 });
  const { data: studio } = await admin.from("studios").select("name,public_name,public_logo_url").eq("id", context.studioId).maybeSingle();
  const studioName = studio?.public_name || studio?.name || "Your studio";
  const pdf = await PDFDocument.create(); const page = pdf.addPage([612,792]); const regular = await pdf.embedFont(StandardFonts.Helvetica); const bold = await pdf.embedFont(StandardFonts.HelveticaBold);
  let brandTextX = 54;
  if (studio?.public_logo_url) {
    try {
      const response = await fetch(studio.public_logo_url, { cache: "no-store", signal: AbortSignal.timeout(5000) });
      const contentType = response.headers.get("content-type")?.split(";")[0]?.toLowerCase();
      const logoBytes = new Uint8Array(await response.arrayBuffer());
      if (response.ok && logoBytes.length <= 2 * 1024 * 1024 && (contentType === "image/png" || contentType === "image/jpeg")) {
        const logo = contentType === "image/png" ? await pdf.embedPng(logoBytes) : await pdf.embedJpg(logoBytes);
        const natural = logo.scale(1);
        const scale = Math.min(74 / natural.width, 42 / natural.height, 1);
        const width = natural.width * scale;
        const height = natural.height * scale;
        page.drawImage(logo, { x:54, y:718, width, height });
        brandTextX = 54 + width + 12;
      }
    } catch {
      // Certificate generation must continue even when a remote logo cannot be loaded.
    }
  }
  page.drawText(studioName, { x:brandTextX, y:735, size:13, font:bold, color:rgb(.35,.12,.45), maxWidth:612-brandTextX-54 }); page.drawText("Completion Certificate", { x:54, y:695, size:24, font:bold, color:rgb(.08,.08,.12) });
  page.drawText("This certificate summarizes the recorded signing event and file integrity values.", { x:54, y:668, size:10, font:regular, color:rgb(.35,.35,.42) });
  line(page, regular, "Document", envelope.title, 620); line(page, regular, "Signer", `${envelope.signer_name} <${envelope.signer_email}>`, 596); line(page, regular, "Completed", envelope.completed_at ? new Date(envelope.completed_at).toLocaleString() : "—", 572); line(page, regular, "Timezone", envelope.signed_timezone ?? "—", 548); line(page, regular, "Signature method", envelope.signature_method ?? "—", 524); line(page, regular, "Envelope ID", envelope.id, 500); line(page, regular, "Source SHA-256", envelope.source_sha256, 462); line(page, regular, "Signed SHA-256", envelope.signed_sha256 ?? "—", 430);
  page.drawText("Electronic signature consent", { x:54, y:382, size:11, font:bold, color:rgb(.08,.08,.12) }); page.drawText(envelope.consent_text || "Consent recorded during signing.", { x:54, y:358, size:9, font:regular, color:rgb(.25,.25,.3), maxWidth:500, lineHeight:13 });
  page.drawText(`Generated by DanceFlow Sign on behalf of ${studioName}`, { x:54, y:54, size:9, font:regular, color:rgb(.45,.45,.5), maxWidth:500 });
  const bytes = await pdf.save(); const filename = `${String(envelope.title).replace(/[^a-z0-9]+/gi,"-").replace(/^-|-$/g,"").toLowerCase() || "document"}-certificate.pdf`;
  return new NextResponse(Buffer.from(bytes), { headers: { "Content-Type":"application/pdf", "Content-Disposition":`attachment; filename="${filename}"`, "Cache-Control":"private, no-store" } });
}
