export type AriaOperationalArea =
  | "front_desk"
  | "client_relations"
  | "scheduling"
  | "sales_retention"
  | "marketing"
  | "billing_payments"
  | "documents"
  | "events"
  | "staff_payroll"
  | "retail_inventory"
  | "studio_health";

export type AriaDeliveryMode =
  | "internal_only"
  | "suggestion_only"
  | "draft_for_review"
  | "auto_send";

export type AriaAutomationRisk = "low" | "medium" | "high";

export type AriaCoverageStatus =
  | "implemented"
  | "partially_implemented"
  | "planned";

export type AriaOperationalAutomation = {
  ruleKey: string;
  area: AriaOperationalArea;
  label: string;
  ownerOutcome: string;
  trigger: string;
  ariaDecision: string;
  defaultAction: string;
  defaultDeliveryMode: AriaDeliveryMode;
  reversible: boolean;
  risk: AriaAutomationRisk;
  escalationCondition: string;
  requiredPermission: string;
  auditRecord: string;
  cadence: string;
  enabledByDefault: boolean;
  coverageStatus: AriaCoverageStatus;
  existingRuleKeys?: string[];
};

export const ARIA_OPERATIONAL_AREAS: Array<{
  key: AriaOperationalArea;
  label: string;
  description: string;
}> = [
  {
    key: "front_desk",
    label: "Front Desk",
    description:
      "Routine requests, confirmations, reminders, and operational follow-through.",
  },
  {
    key: "client_relations",
    label: "Client Relationships",
    description:
      "Welcoming, follow-up, service recovery, and ongoing relationship care.",
  },
  {
    key: "scheduling",
    label: "Scheduling",
    description:
      "Booking readiness, conflicts, gaps, waitlists, and instructor coverage.",
  },
  {
    key: "sales_retention",
    label: "Sales and Retention",
    description:
      "Lead conversion, rebooking, package renewal, membership care, and reactivation.",
  },
  {
    key: "marketing",
    label: "Marketing",
    description:
      "Campaign preparation, audience opportunities, event promotion, and content support.",
  },
  {
    key: "billing_payments",
    label: "Billing and Payments",
    description:
      "Payment exceptions, balances, failed renewals, and safe financial follow-up.",
  },
  {
    key: "documents",
    label: "Documents",
    description:
      "Signature reminders, expiration checks, and document-completion follow-through.",
  },
  {
    key: "events",
    label: "Events",
    description:
      "Registration, payment, attendance, cost, and profitability exceptions.",
  },
  {
    key: "staff_payroll",
    label: "Staff and Payroll",
    description:
      "Substitutions, time-entry gaps, payroll-prep exceptions, and staff coordination.",
  },
  {
    key: "retail_inventory",
    label: "Retail and Inventory",
    description:
      "Low-stock, fulfillment, entitlement, and commerce exceptions.",
  },
  {
    key: "studio_health",
    label: "Studio Health",
    description:
      "Data quality, onboarding gaps, app adoption, and operational-risk monitoring.",
  },
];

export const ARIA_OPERATIONAL_AUTOMATION_MATRIX: AriaOperationalAutomation[] = [
  {
    ruleKey: "aria_booking_request_aging",
    area: "front_desk",
    label: "Aging booking requests",
    ownerOutcome: "Booking requests do not sit unanswered.",
    trigger: "A booking request remains pending beyond the studio response window.",
    ariaDecision: "Determine whether the request still needs staff review.",
    defaultAction: "Create a high-priority internal review task.",
    defaultDeliveryMode: "internal_only",
    reversible: true,
    risk: "medium",
    escalationCondition: "Requested time is no longer available or client/instructor details conflict.",
    requiredPermission: "Manage schedule",
    auditRecord: "Automation action and lifecycle event",
    cadence: "Hourly",
    enabledByDefault: true,
    coverageStatus: "implemented",
    existingRuleKeys: ["pending_booking_request"],
  },
  {
    ruleKey: "aria_appointment_confirmation_gap",
    area: "front_desk",
    label: "Unconfirmed appointment follow-up",
    ownerOutcome: "Upcoming appointments are confirmed before staff time is lost.",
    trigger: "An upcoming appointment remains unconfirmed inside the reminder window.",
    ariaDecision: "Check cancellation, confirmation, and communication history.",
    defaultAction: "Prepare a confirmation reminder.",
    defaultDeliveryMode: "draft_for_review",
    reversible: true,
    risk: "low",
    escalationCondition: "Client has opted out, appointment changed, or repeated reminders already failed.",
    requiredPermission: "View schedule and communicate with clients",
    auditRecord: "Automation action, outbound delivery, and outcome verification",
    cadence: "Daily",
    enabledByDefault: true,
    coverageStatus: "implemented",
  },
  {
    ruleKey: "aria_cancellation_follow_up",
    area: "front_desk",
    label: "Cancellation follow-up",
    ownerOutcome: "Cancelled lesson time has a clear next step.",
    trigger: "A client cancellation leaves no future appointment.",
    ariaDecision: "Determine whether rebooking outreach is appropriate.",
    defaultAction: "Prepare a rebooking message with the client portal link.",
    defaultDeliveryMode: "draft_for_review",
    reversible: true,
    risk: "low",
    escalationCondition: "Cancellation reason indicates dissatisfaction, illness, dispute, or do-not-contact preference.",
    requiredPermission: "View schedule and communicate with clients",
    auditRecord: "Automation action and outbound delivery",
    cadence: "Event-driven",
    enabledByDefault: true,
    coverageStatus: "implemented",
  },
  {
    ruleKey: "aria_first_lesson_follow_up",
    area: "client_relations",
    label: "First lesson follow-up",
    ownerOutcome: "Every new dancer receives a timely, personal next step.",
    trigger: "A client completes their first lesson.",
    ariaDecision: "Confirm the lesson was completed and no follow-up already exists.",
    defaultAction: "Prepare a thank-you and next-lesson message.",
    defaultDeliveryMode: "auto_send",
    reversible: false,
    risk: "low",
    escalationCondition: "Attendance is disputed, service complaint exists, or client opted out.",
    requiredPermission: "Communicate with clients",
    auditRecord: "Automation action, delivery record, and outcome verification",
    cadence: "Event-driven",
    enabledByDefault: true,
    coverageStatus: "implemented",
    existingRuleKeys: ["aria_intro_no_purchase", "first_lesson_follow_up"],
  },
  {
    ruleKey: "aria_no_show_service_recovery",
    area: "client_relations",
    label: "No-show service recovery",
    ownerOutcome: "No-shows receive appropriate follow-up without insensitive automation.",
    trigger: "An appointment is marked no-show.",
    ariaDecision: "Check history, policy, balance impact, and prior outreach.",
    defaultAction: "Prepare a supportive follow-up or internal review task.",
    defaultDeliveryMode: "draft_for_review",
    reversible: true,
    risk: "medium",
    escalationCondition: "Repeated no-shows, fee dispute, package depletion, or sensitive client notes.",
    requiredPermission: "View attendance, balances, and communicate with clients",
    auditRecord: "Automation action and delivery record",
    cadence: "Event-driven",
    enabledByDefault: true,
    coverageStatus: "implemented",
  },
  {
    ruleKey: "aria_unsigned_document",
    area: "documents",
    label: "Unsigned document reminder",
    ownerOutcome: "Required documents are completed before participation.",
    trigger: "A required document remains unsigned inside the due window.",
    ariaDecision: "Confirm the request is active, not waived, voided, or superseded.",
    defaultAction: "Prepare a secure signing reminder.",
    defaultDeliveryMode: "auto_send",
    reversible: false,
    risk: "low",
    escalationCondition: "Document is expired, superseded, disputed, or signing link is invalid.",
    requiredPermission: "View documents and communicate with clients",
    auditRecord: "Automation action, outbound delivery, and signing outcome",
    cadence: "Daily",
    enabledByDefault: true,
    coverageStatus: "implemented",
    existingRuleKeys: ["unsigned_document"],
  },
  {
    ruleKey: "aria_document_expiration",
    area: "documents",
    label: "Expiring document review",
    ownerOutcome: "Time-sensitive agreements are renewed before they lapse.",
    trigger: "A document or certification approaches expiration.",
    ariaDecision: "Determine whether renewal or replacement is required.",
    defaultAction: "Create a renewal task or prepare a replacement request.",
    defaultDeliveryMode: "draft_for_review",
    reversible: true,
    risk: "medium",
    escalationCondition: "Legal terms changed or prior request must be superseded.",
    requiredPermission: "Manage documents",
    auditRecord: "Automation action and document audit trail",
    cadence: "Daily",
    enabledByDefault: true,
    coverageStatus: "implemented",
  },
  {
    ruleKey: "aria_stale_active_student",
    area: "sales_retention",
    label: "Active client rebooking",
    ownerOutcome: "Active dancers maintain lesson momentum.",
    trigger: "An active client has no future appointment.",
    ariaDecision: "Confirm recent activity and whether rebooking outreach is appropriate.",
    defaultAction: "Send a rebooking prompt with schedule access.",
    defaultDeliveryMode: "auto_send",
    reversible: false,
    risk: "low",
    escalationCondition: "Client is paused, inactive, opted out, or recently declined outreach.",
    requiredPermission: "View schedule and communicate with clients",
    auditRecord: "Automation action, delivery record, and rebooking outcome",
    cadence: "Daily",
    enabledByDefault: true,
    coverageStatus: "implemented",
    existingRuleKeys: ["no_upcoming_lesson"],
  },
  {
    ruleKey: "aria_low_package_balance",
    area: "sales_retention",
    label: "Low package balance outreach",
    ownerOutcome: "Clients renew before lesson momentum is interrupted.",
    trigger: "A usable package balance reaches the studio threshold.",
    ariaDecision: "Confirm the balance is current and another package is not already active.",
    defaultAction: "Send a renewal reminder.",
    defaultDeliveryMode: "auto_send",
    reversible: false,
    risk: "low",
    escalationCondition: "Balance dispute, overlapping package, refund, or membership entitlement conflict.",
    requiredPermission: "View packages and communicate with clients",
    auditRecord: "Automation action, delivery record, and purchase outcome",
    cadence: "Daily",
    enabledByDefault: true,
    coverageStatus: "implemented",
    existingRuleKeys: ["low_package_balance"],
  },
  {
    ruleKey: "aria_package_expiring",
    area: "sales_retention",
    label: "Package expiration outreach",
    ownerOutcome: "Clients receive notice before usable credits expire.",
    trigger: "An active package approaches expiration.",
    ariaDecision: "Confirm remaining credits and extension or renewal eligibility.",
    defaultAction: "Send an expiration reminder.",
    defaultDeliveryMode: "auto_send",
    reversible: false,
    risk: "low",
    escalationCondition: "Package is disputed, frozen, refunded, or subject to a manual extension.",
    requiredPermission: "View packages and communicate with clients",
    auditRecord: "Automation action and outbound delivery",
    cadence: "Daily",
    enabledByDefault: true,
    coverageStatus: "implemented",
  },
  {
    ruleKey: "aria_membership_past_due",
    area: "billing_payments",
    label: "Past-due membership follow-up",
    ownerOutcome: "Past-due memberships receive timely follow-up without automatic financial changes.",
    trigger: "A membership billing period becomes past due.",
    ariaDecision: "Confirm payment status, external payment state, and prior outreach.",
    defaultAction: "Send a payment reminder and notify staff.",
    defaultDeliveryMode: "auto_send",
    reversible: false,
    risk: "medium",
    escalationCondition: "Payment dispute, chargeback, external payment uncertainty, or repeated failure.",
    requiredPermission: "View membership billing and communicate with clients",
    auditRecord: "Automation action, delivery record, and payment outcome",
    cadence: "Daily",
    enabledByDefault: true,
    coverageStatus: "implemented",
  },
  {
    ruleKey: "aria_membership_canceling",
    area: "sales_retention",
    label: "Canceling membership outreach",
    ownerOutcome: "The studio has a chance to understand and respond to cancellation risk.",
    trigger: "A membership is scheduled to cancel.",
    ariaDecision: "Check reason, history, and whether retention outreach is appropriate.",
    defaultAction: "Send a supportive retention message and notify staff.",
    defaultDeliveryMode: "draft_for_review",
    reversible: true,
    risk: "medium",
    escalationCondition: "Complaint, legal issue, payment dispute, or explicit no-contact request.",
    requiredPermission: "View memberships and communicate with clients",
    auditRecord: "Automation action and delivery record",
    cadence: "Event-driven",
    enabledByDefault: true,
    coverageStatus: "implemented",
  },
  {
    ruleKey: "aria_payment_exception",
    area: "billing_payments",
    label: "Payment exception review",
    ownerOutcome: "Failed and pending payments are resolved without unsafe automated charges.",
    trigger: "A payment is pending, failed, mismatched, or unresolved.",
    ariaDecision: "Classify the exception and identify the safest next step.",
    defaultAction: "Create a high-priority internal review task.",
    defaultDeliveryMode: "internal_only",
    reversible: true,
    risk: "high",
    escalationCondition: "Always requires staff review before charge, refund, retry, waiver, or access change.",
    requiredPermission: "Manage payments",
    auditRecord: "Automation action, review event, and payment audit record",
    cadence: "Hourly",
    enabledByDefault: true,
    coverageStatus: "implemented",
  },
  {
    ruleKey: "aria_external_payment_missing",
    area: "billing_payments",
    label: "Missing external payment",
    ownerOutcome: "Externally paid memberships and packages do not remain incorrectly unpaid.",
    trigger: "A renewal or period is due but no linked external payment is recorded.",
    ariaDecision: "Check ledger, manual payment history, and entitlement period.",
    defaultAction: "Create a reconciliation task.",
    defaultDeliveryMode: "internal_only",
    reversible: true,
    risk: "high",
    escalationCondition: "Always requires financial review before changing payment or entitlement state.",
    requiredPermission: "Manage payments and memberships",
    auditRecord: "Automation action and reconciliation audit",
    cadence: "Daily",
    enabledByDefault: true,
    coverageStatus: "implemented",
  },
  {
    ruleKey: "aria_lead_acknowledgement",
    area: "client_relations",
    label: "New lead acknowledgement",
    ownerOutcome: "Every new inquiry receives an immediate response.",
    trigger: "A new lead is created from a public form, event, referral, or manual entry.",
    ariaDecision: "Confirm consent, source, and whether a duplicate active conversation exists.",
    defaultAction: "Send a branded acknowledgement with the correct next step.",
    defaultDeliveryMode: "auto_send",
    reversible: false,
    risk: "low",
    escalationCondition: "No consent, duplicate lead, invalid contact, or sensitive inquiry.",
    requiredPermission: "View leads and communicate",
    auditRecord: "Automation action, delivery record, and lead response outcome",
    cadence: "Event-driven",
    enabledByDefault: true,
    coverageStatus: "implemented",
  },
  {
    ruleKey: "aria_lead_follow_up_sequence",
    area: "sales_retention",
    label: "Lead follow-up sequence",
    ownerOutcome: "Promising leads do not disappear because staff became busy.",
    trigger: "A lead has not responded or booked after the acknowledgement.",
    ariaDecision: "Select the appropriate follow-up step and stop conditions.",
    defaultAction: "Send the next approved follow-up message.",
    defaultDeliveryMode: "draft_for_review",
    reversible: true,
    risk: "medium",
    escalationCondition: "Negative response, opt-out, duplicate contact, or high-value personalized opportunity.",
    requiredPermission: "Manage leads and communicate",
    auditRecord: "Automation action, sequence state, delivery record, and outcome",
    cadence: "Daily",
    enabledByDefault: true,
    coverageStatus: "implemented",
  },
  {
    ruleKey: "aria_inactive_client_reactivation",
    area: "sales_retention",
    label: "Inactive client reactivation",
    ownerOutcome: "Former dancers receive relevant, respectful reactivation opportunities.",
    trigger: "A previously active client reaches the inactivity threshold.",
    ariaDecision: "Assess recent activity, opt-out state, and appropriate offer or message.",
    defaultAction: "Prepare a reactivation message.",
    defaultDeliveryMode: "draft_for_review",
    reversible: true,
    risk: "medium",
    escalationCondition: "Complaint history, balance dispute, opt-out, or sensitive notes.",
    requiredPermission: "View clients and communicate",
    auditRecord: "Automation action, delivery record, and reactivation outcome",
    cadence: "Weekly",
    enabledByDefault: true,
    coverageStatus: "implemented",
  },
  {
    ruleKey: "aria_schedule_conflict",
    area: "scheduling",
    label: "Schedule conflict review",
    ownerOutcome: "Instructor, client, and room conflicts are caught before the appointment.",
    trigger: "An appointment overlaps another required resource.",
    ariaDecision: "Classify instructor, client, location, or room conflict.",
    defaultAction: "Create an urgent internal resolution task.",
    defaultDeliveryMode: "internal_only",
    reversible: true,
    risk: "high",
    escalationCondition: "Always requires staff choice before moving or cancelling an appointment.",
    requiredPermission: "Manage schedule",
    auditRecord: "Automation action and schedule change audit",
    cadence: "Event-driven and daily",
    enabledByDefault: true,
    coverageStatus: "implemented",
  },
  {
    ruleKey: "aria_instructor_coverage_gap",
    area: "scheduling",
    label: "Instructor coverage gap",
    ownerOutcome: "Instructor absences and unassigned lessons are resolved early.",
    trigger: "An upcoming appointment lacks an available assigned instructor.",
    ariaDecision: "Identify qualified available substitutes.",
    defaultAction: "Prepare substitute options for staff approval.",
    defaultDeliveryMode: "suggestion_only",
    reversible: true,
    risk: "high",
    escalationCondition: "Always requires staff approval before reassignment or client communication.",
    requiredPermission: "Manage schedule and instructors",
    auditRecord: "Automation action, approval event, and assignment audit",
    cadence: "Hourly",
    enabledByDefault: true,
    coverageStatus: "implemented",
  },
  {
    ruleKey: "aria_class_capacity",
    area: "scheduling",
    label: "Class capacity and waitlist movement",
    ownerOutcome: "Open spaces are filled and over-capacity classes are resolved.",
    trigger: "Class capacity changes or a cancellation opens a seat.",
    ariaDecision: "Determine the next eligible waitlisted dancer and policy constraints.",
    defaultAction: "Prepare a waitlist promotion or capacity exception task.",
    defaultDeliveryMode: "draft_for_review",
    reversible: true,
    risk: "medium",
    escalationCondition: "Eligibility, payment, document, age, or membership requirements are unresolved.",
    requiredPermission: "Manage classes and communicate",
    auditRecord: "Automation action, roster change, and delivery record",
    cadence: "Event-driven",
    enabledByDefault: true,
    coverageStatus: "implemented",
  },
  {
    ruleKey: "aria_marketing_opportunity",
    area: "marketing",
    label: "Marketing opportunity suggestions",
    ownerOutcome: "The studio receives timely campaign ideas based on real business activity.",
    trigger: "A segment, event, enrollment gap, or seasonal opportunity meets a recommended threshold.",
    ariaDecision: "Identify the audience, goal, and suggested campaign.",
    defaultAction: "Create a campaign brief and draft.",
    defaultDeliveryMode: "suggestion_only",
    reversible: true,
    risk: "medium",
    escalationCondition: "Audience consent, offer, budget, or brand decision is unresolved.",
    requiredPermission: "Manage marketing",
    auditRecord: "Automation suggestion and campaign audit",
    cadence: "Weekly",
    enabledByDefault: true,
    coverageStatus: "implemented",
  },
  {
    ruleKey: "aria_event_promotion_gap",
    area: "marketing",
    label: "Event promotion gap",
    ownerOutcome: "Events with weak registration receive a clear promotional next step.",
    trigger: "Registration pace falls below the expected curve.",
    ariaDecision: "Assess capacity, time remaining, audience, and prior promotion.",
    defaultAction: "Prepare a targeted campaign recommendation.",
    defaultDeliveryMode: "suggestion_only",
    reversible: true,
    risk: "medium",
    escalationCondition: "Pricing, discount, audience, or event viability requires owner judgment.",
    requiredPermission: "Manage events and marketing",
    auditRecord: "Automation suggestion and campaign audit",
    cadence: "Daily",
    enabledByDefault: true,
    coverageStatus: "implemented",
  },
  {
    ruleKey: "aria_event_unpaid_registration",
    area: "events",
    label: "Unpaid event registrations",
    ownerOutcome: "Event payment exceptions are resolved before participation.",
    trigger: "An event registration remains unpaid or partially paid.",
    ariaDecision: "Confirm registration and payment state.",
    defaultAction: "Create an internal financial review task.",
    defaultDeliveryMode: "internal_only",
    reversible: true,
    risk: "high",
    escalationCondition: "Always requires review before charge, cancellation, waiver, or access change.",
    requiredPermission: "Manage events and payments",
    auditRecord: "Automation action and financial audit",
    cadence: "Hourly",
    enabledByDefault: true,
    coverageStatus: "implemented",
  },
  {
    ruleKey: "aria_event_missing_costs",
    area: "events",
    label: "Missing event costs",
    ownerOutcome: "Event profitability is not trusted until costs are complete.",
    trigger: "An event has revenue but incomplete expected costs.",
    ariaDecision: "Identify missing cost categories.",
    defaultAction: "Create a high-priority accounting completion task.",
    defaultDeliveryMode: "internal_only",
    reversible: true,
    risk: "high",
    escalationCondition: "Always requires staff entry or confirmation.",
    requiredPermission: "Manage events and accounting",
    auditRecord: "Automation action and accounting audit",
    cadence: "Daily",
    enabledByDefault: true,
    coverageStatus: "implemented",
  },
  {
    ruleKey: "aria_event_loss",
    area: "events",
    label: "Event loss review",
    ownerOutcome: "Below-break-even events receive attention without automatic pricing changes.",
    trigger: "Final or projected event profitability falls below the review threshold.",
    ariaDecision: "Confirm revenue and cost completeness.",
    defaultAction: "Create an owner review task.",
    defaultDeliveryMode: "internal_only",
    reversible: true,
    risk: "high",
    escalationCondition: "Always requires owner judgment.",
    requiredPermission: "View event accounting",
    auditRecord: "Automation action and profitability snapshot",
    cadence: "Daily",
    enabledByDefault: true,
    coverageStatus: "implemented",
  },
  {
    ruleKey: "aria_event_low_checkin",
    area: "events",
    label: "Event attendance-quality review",
    ownerOutcome: "Registration and actual attendance discrepancies are reviewed.",
    trigger: "Check-in quality or attendance completion falls below threshold.",
    ariaDecision: "Determine whether attendance records are incomplete or actual turnout was low.",
    defaultAction: "Create an attendance review task.",
    defaultDeliveryMode: "internal_only",
    reversible: true,
    risk: "medium",
    escalationCondition: "Attendance changes affect billing, entitlements, or reporting.",
    requiredPermission: "Manage events and attendance",
    auditRecord: "Automation action and attendance audit",
    cadence: "After event close",
    enabledByDefault: true,
    coverageStatus: "implemented",
  },
  {
    ruleKey: "aria_payroll_missing_data",
    area: "staff_payroll",
    label: "Payroll data completion",
    ownerOutcome: "Payroll exports are not prepared with missing instructor or appointment data.",
    trigger: "Payroll period contains missing rate, role, attendance, or payout details.",
    ariaDecision: "Identify the exact records blocking payroll readiness.",
    defaultAction: "Create a grouped payroll exception task.",
    defaultDeliveryMode: "internal_only",
    reversible: true,
    risk: "high",
    escalationCondition: "Always requires authorized payroll review.",
    requiredPermission: "Manage payroll",
    auditRecord: "Automation action and payroll-prep audit",
    cadence: "Daily during open payroll period",
    enabledByDefault: true,
    coverageStatus: "implemented",
  },
  {
    ruleKey: "aria_staff_task_reminder",
    area: "staff_payroll",
    label: "Staff operational reminders",
    ownerOutcome: "Assigned operational tasks do not quietly become overdue.",
    trigger: "A staff task approaches or passes its due time.",
    ariaDecision: "Check completion, assignment, and whether escalation is needed.",
    defaultAction: "Notify the assigned staff member or escalate internally.",
    defaultDeliveryMode: "internal_only",
    reversible: true,
    risk: "low",
    escalationCondition: "Task remains overdue after reminder or lacks an assignee.",
    requiredPermission: "View assigned operational tasks",
    auditRecord: "Automation action and task event",
    cadence: "Hourly",
    enabledByDefault: true,
    coverageStatus: "implemented",
  },
  {
    ruleKey: "aria_inventory_low_stock",
    area: "retail_inventory",
    label: "Low inventory review",
    ownerOutcome: "Retail products do not unexpectedly run out.",
    trigger: "On-hand inventory reaches the reorder threshold.",
    ariaDecision: "Confirm pending orders, reserved stock, and recent sales pace.",
    defaultAction: "Create a reorder suggestion.",
    defaultDeliveryMode: "suggestion_only",
    reversible: true,
    risk: "medium",
    escalationCondition: "Purchase amount, vendor, or reorder quantity requires approval.",
    requiredPermission: "Manage inventory",
    auditRecord: "Automation suggestion and inventory snapshot",
    cadence: "Daily",
    enabledByDefault: true,
    coverageStatus: "implemented",
  },
  {
    ruleKey: "aria_order_fulfillment_exception",
    area: "retail_inventory",
    label: "Order fulfillment exception",
    ownerOutcome: "Paid orders and digital entitlements are fulfilled correctly.",
    trigger: "A paid order remains unfulfilled or entitlement creation fails.",
    ariaDecision: "Classify stock, payment, fulfillment, or entitlement failure.",
    defaultAction: "Create an urgent internal task.",
    defaultDeliveryMode: "internal_only",
    reversible: true,
    risk: "high",
    escalationCondition: "Always requires staff review before refund or manual fulfillment.",
    requiredPermission: "Manage commerce",
    auditRecord: "Automation action, order audit, and entitlement audit",
    cadence: "Hourly",
    enabledByDefault: true,
    coverageStatus: "implemented",
  },
  {
    ruleKey: "aria_student_app_adoption",
    area: "studio_health",
    label: "Student app adoption",
    ownerOutcome: "Active dancers can access booking, documents, wallet, and studio updates.",
    trigger: "An active client remains unlinked or has not activated app access.",
    ariaDecision: "Check invitation, linking, notification, and account status.",
    defaultAction: "Prepare an app invitation or create a linking exception task.",
    defaultDeliveryMode: "draft_for_review",
    reversible: true,
    risk: "medium",
    escalationCondition: "Duplicate identity, parent/child account, bounced invitation, or prior opt-out.",
    requiredPermission: "Manage clients and portal access",
    auditRecord: "Automation action, delivery record, and linking outcome",
    cadence: "Weekly",
    enabledByDefault: true,
    coverageStatus: "implemented",
  },
  {
    ruleKey: "aria_data_quality_exception",
    area: "studio_health",
    label: "Operational data quality",
    ownerOutcome: "Duplicate, incomplete, and contradictory records are surfaced before they cause errors.",
    trigger: "A data-quality rule detects a duplicate, missing relationship, invalid state, or reconciliation mismatch.",
    ariaDecision: "Classify safe automatic repair versus staff decision.",
    defaultAction: "Repair deterministic issues or create a focused exception task.",
    defaultDeliveryMode: "internal_only",
    reversible: true,
    risk: "medium",
    escalationCondition: "Any merge, deletion, financial change, legal record, or ambiguous identity.",
    requiredPermission: "Varies by affected record",
    auditRecord: "Automation action and before/after evidence",
    cadence: "Daily",
    enabledByDefault: true,
    coverageStatus: "implemented",
  },
];

export function getAriaOperationalArea(area: AriaOperationalArea) {
  return ARIA_OPERATIONAL_AREAS.find((item) => item.key === area) ?? null;
}

export function getAriaOperationalAutomation(ruleKey: string) {
  return (
    ARIA_OPERATIONAL_AUTOMATION_MATRIX.find(
      (item) =>
        item.ruleKey === ruleKey || item.existingRuleKeys?.includes(ruleKey),
    ) ?? null
  );
}

export function getAriaCoverageSummary() {
  return ARIA_OPERATIONAL_AREAS.map((area) => {
    const automations = ARIA_OPERATIONAL_AUTOMATION_MATRIX.filter(
      (item) => item.area === area.key,
    );

    return {
      area: area.key,
      label: area.label,
      total: automations.length,
      implemented: automations.filter(
        (item) => item.coverageStatus === "implemented",
      ).length,
      partiallyImplemented: automations.filter(
        (item) => item.coverageStatus === "partially_implemented",
      ).length,
      planned: automations.filter(
        (item) => item.coverageStatus === "planned",
      ).length,
    };
  });
}
