import Link from "next/link";
import { createClient } from "@/lib/supabase/server";
import { getCurrentStudioContext } from "@/lib/auth/studio";
import { createSignEnvelopeAction } from "./actions";

function formatDate(value: string | null) { if (!value) return "—"; return new Intl.DateTimeFormat("en-US", { month: "short", day: "numeric", year: "numeric", hour: "numeric", minute: "2-digit" }).format(new Date(value)); }
export default async function DanceFlowSignPage({ searchParams }: { searchParams: Promise<{ success?: string; error?: string }> }) {
  const params = await searchParams; const context = await getCurrentStudioContext(); const supabase = await createClient();
  const { data: envelopes, error } = await supabase.from("document_sign_envelopes").select("id,title,signer_name,signer_email,status,expires_at,sent_at,viewed_at,completed_at,created_at").eq("studio_id", context.studioId).order("created_at", { ascending: false }).limit(50);
  if (error) throw error;
  return <main className="mx-auto max-w-6xl space-y-6 px-4 py-6 md:px-8">
    <div className="flex flex-col gap-4 rounded-[28px] border border-slate-200 bg-white p-6 shadow-sm md:flex-row md:items-end md:justify-between"><div><p className="text-xs font-semibold uppercase tracking-[0.2em] text-violet-700">DanceFlow Sign</p><h1 className="mt-2 text-3xl font-semibold tracking-tight text-slate-950">Send a PDF for signature</h1><p className="mt-2 max-w-2xl text-sm leading-7 text-slate-600">Upload a PDF, place the fields exactly where they belong, and let DanceFlow handle secure delivery and completion tracking.</p></div><Link href="/app/documents" className="rounded-xl border border-slate-300 px-4 py-2 text-sm font-semibold text-slate-700">Back to Documents</Link></div>
    {params.success === "sent" ? <div className="rounded-2xl border border-emerald-200 bg-emerald-50 p-4 text-sm text-emerald-800">Signing request queued successfully.</div> : null}
    {params.error ? <div className="rounded-2xl border border-rose-200 bg-rose-50 p-4 text-sm text-rose-800">The signing request could not be completed: {params.error.replaceAll("_", " ")}.</div> : null}
    <section className="rounded-[28px] border border-slate-200 bg-white p-6 shadow-sm"><h2 className="text-xl font-semibold text-slate-950">New signing request</h2><p className="mt-2 text-sm text-slate-600">Start with the PDF and signer. You will place and configure fields before anything is sent.</p><form action={createSignEnvelopeAction} className="mt-6 grid gap-4 md:grid-cols-2"><label className="text-sm font-medium text-slate-800">Document title<input name="title" required className="mt-2 w-full rounded-xl border border-slate-300 px-3 py-2.5" /></label><label className="text-sm font-medium text-slate-800">PDF file<input name="pdfFile" type="file" accept="application/pdf,.pdf" required className="mt-2 block w-full rounded-xl border border-slate-300 p-2 text-sm" /></label><label className="text-sm font-medium text-slate-800">Signer name<input name="signerName" required className="mt-2 w-full rounded-xl border border-slate-300 px-3 py-2.5" /></label><label className="text-sm font-medium text-slate-800">Signer email<input name="signerEmail" type="email" required className="mt-2 w-full rounded-xl border border-slate-300 px-3 py-2.5" /></label><label className="text-sm font-medium text-slate-800">Link expires in<select name="expiresInDays" defaultValue="7" className="mt-2 w-full rounded-xl border border-slate-300 px-3 py-2.5"><option value="3">3 days</option><option value="7">7 days</option><option value="14">14 days</option><option value="30">30 days</option></select></label><div className="flex items-end"><button className="w-full rounded-xl bg-[var(--brand-primary)] px-4 py-3 text-sm font-semibold text-white">Upload and place fields</button></div></form></section>
    <section className="rounded-[28px] border border-slate-200 bg-white p-6 shadow-sm"><h2 className="text-xl font-semibold text-slate-950">Recent signing requests</h2><div className="mt-4 overflow-x-auto"><table className="min-w-full text-left text-sm"><thead className="border-b border-slate-200 text-xs uppercase tracking-wide text-slate-500"><tr><th className="py-3 pr-4">Document</th><th className="py-3 pr-4">Signer</th><th className="py-3 pr-4">Status</th><th className="py-3 pr-4">Sent</th><th className="py-3">Expires</th></tr></thead><tbody>{(envelopes ?? []).map((item) => <tr key={item.id} className="border-b border-slate-100"><td className="py-4 pr-4 font-semibold text-slate-950">{item.status === "draft" ? <Link className="text-violet-700 hover:underline" href={`/app/documents/sign/${item.id}/edit`}>{item.title}</Link> : item.title}</td><td className="py-4 pr-4"><div>{item.signer_name}</div><div className="text-xs text-slate-500">{item.signer_email}</div></td><td className="py-4 pr-4 capitalize">{item.status}</td><td className="py-4 pr-4 text-slate-600">{formatDate(item.sent_at)}</td><td className="py-4 text-slate-600">{formatDate(item.expires_at)}</td></tr>)}{!envelopes?.length ? <tr><td colSpan={5} className="py-8 text-center text-slate-500">No signing requests yet.</td></tr> : null}</tbody></table></div></section>
  </main>;
}