begin;

-- =============================================================================
-- DanceFlow Payroll Prep V1 — Data Foundation
-- =============================================================================
-- Scope:
--   • Keep sensitive payroll attributes out of the general instructors table.
--   • Add payroll profiles, pay periods, payroll batches, earning snapshots,
--     and append-only compensation history.
--   • Limit payroll preparation to studio owners/admins.
--   • Reserve final paid actions for studio owners.
--   • Remove legacy hard-delete access.
--   • Do not change instructor earning calculation logic in this migration.
-- =============================================================================

-- -----------------------------------------------------------------------------
-- 1. Sensitive instructor payroll profiles
-- -----------------------------------------------------------------------------

create table if not exists public.instructor_payroll_profiles (
  id uuid primary key default gen_random_uuid(),
  studio_id uuid not null references public.studios(id) on delete cascade,
  instructor_id uuid not null references public.instructors(id) on delete cascade,

  worker_classification text not null default 'not_set'
    check (worker_classification in ('not_set', 'contractor', 'employee', 'owner')),

  payroll_active boolean not null default true,
  external_payroll_id text,
  payroll_notes text,

  created_by uuid references public.profiles(id) on delete set null,
  updated_by uuid references public.profiles(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),

  unique (studio_id, instructor_id)
);

create index if not exists idx_instructor_payroll_profiles_studio
  on public.instructor_payroll_profiles (studio_id, instructor_id);

create unique index if not exists idx_instructor_payroll_profiles_external_id
  on public.instructor_payroll_profiles (studio_id, external_payroll_id)
  where external_payroll_id is not null;

-- Seed a non-sensitive default profile for every existing instructor.
insert into public.instructor_payroll_profiles (
  studio_id,
  instructor_id,
  worker_classification,
  payroll_active
)
select
  i.studio_id,
  i.id,
  'not_set',
  true
from public.instructors i
where not exists (
  select 1
  from public.instructor_payroll_profiles ipp
  where ipp.studio_id = i.studio_id
    and ipp.instructor_id = i.id
);

-- -----------------------------------------------------------------------------
-- 2. Pay periods
-- -----------------------------------------------------------------------------

create table if not exists public.payroll_pay_periods (
  id uuid primary key default gen_random_uuid(),
  studio_id uuid not null references public.studios(id) on delete cascade,

  period_start date not null,
  period_end date not null,
  pay_date date,
  status text not null default 'open'
    check (status in ('open', 'in_review', 'approved', 'paid', 'void')),

  compensation_total numeric not null default 0,
  reimbursement_total numeric not null default 0,
  deduction_total numeric not null default 0,
  net_payment_total numeric not null default 0,

  approved_at timestamptz,
  approved_by uuid references public.profiles(id) on delete set null,
  paid_at timestamptz,
  paid_by uuid references public.profiles(id) on delete set null,
  voided_at timestamptz,
  voided_by uuid references public.profiles(id) on delete set null,
  void_reason text,
  locked_at timestamptz,

  created_by uuid references public.profiles(id) on delete set null,
  updated_by uuid references public.profiles(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),

  check (period_end >= period_start),
  unique (studio_id, period_start, period_end)
);

create index if not exists idx_payroll_pay_periods_studio_dates
  on public.payroll_pay_periods (studio_id, period_start desc, period_end desc);

create index if not exists idx_payroll_pay_periods_studio_status
  on public.payroll_pay_periods (studio_id, status);

-- -----------------------------------------------------------------------------
-- 3. Payroll batches
-- -----------------------------------------------------------------------------

create table if not exists public.payroll_batches (
  id uuid primary key default gen_random_uuid(),
  studio_id uuid not null references public.studios(id) on delete cascade,
  pay_period_id uuid not null references public.payroll_pay_periods(id) on delete restrict,

  batch_number bigint generated by default as identity,
  provider text not null default 'manual',
  provider_batch_reference text,
  status text not null default 'draft'
    check (status in ('draft', 'in_review', 'approved', 'paid', 'void')),

  compensation_total numeric not null default 0,
  reimbursement_total numeric not null default 0,
  deduction_total numeric not null default 0,
  net_payment_total numeric not null default 0,
  earning_count integer not null default 0,

  approved_at timestamptz,
  approved_by uuid references public.profiles(id) on delete set null,
  paid_at timestamptz,
  paid_by uuid references public.profiles(id) on delete set null,
  payment_method text,
  voided_at timestamptz,
  voided_by uuid references public.profiles(id) on delete set null,
  void_reason text,
  locked_at timestamptz,

  created_by uuid references public.profiles(id) on delete set null,
  updated_by uuid references public.profiles(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),

  unique (studio_id, batch_number)
);

create index if not exists idx_payroll_batches_studio_period
  on public.payroll_batches (studio_id, pay_period_id, created_at desc);

create index if not exists idx_payroll_batches_studio_status
  on public.payroll_batches (studio_id, status);

create unique index if not exists idx_payroll_batches_provider_reference
  on public.payroll_batches (studio_id, provider, provider_batch_reference)
  where provider_batch_reference is not null;

-- -----------------------------------------------------------------------------
-- 4. Extend instructor earnings with payroll snapshots and batch linkage
-- -----------------------------------------------------------------------------

alter table public.instructor_earnings
  add column if not exists pay_period_id uuid
    references public.payroll_pay_periods(id) on delete restrict,
  add column if not exists payroll_batch_id uuid
    references public.payroll_batches(id) on delete restrict,
  add column if not exists worker_classification_snapshot text,
  add column if not exists accounting_category_snapshot text,
  add column if not exists taxable_compensation_amount numeric not null default 0,
  add column if not exists reimbursement_amount numeric not null default 0,
  add column if not exists deduction_amount numeric not null default 0,
  add column if not exists locked_at timestamptz;

do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conrelid = 'public.instructor_earnings'::regclass
      and conname = 'instructor_earnings_worker_classification_snapshot_check'
  ) then
    alter table public.instructor_earnings
      add constraint instructor_earnings_worker_classification_snapshot_check
      check (
        worker_classification_snapshot is null
        or worker_classification_snapshot in ('not_set', 'contractor', 'employee', 'owner')
      );
  end if;
end
$$;

create index if not exists idx_instructor_earnings_pay_period
  on public.instructor_earnings (studio_id, pay_period_id, status);

create index if not exists idx_instructor_earnings_payroll_batch
  on public.instructor_earnings (studio_id, payroll_batch_id, status);

-- Existing rows are absent in the audited dev database, but this keeps the
-- migration safe if another environment already contains compensation data.
update public.instructor_earnings ie
set
  worker_classification_snapshot = coalesce(
    ie.worker_classification_snapshot,
    ipp.worker_classification,
    'not_set'
  ),
  accounting_category_snapshot = coalesce(
    ie.accounting_category_snapshot,
    case
      when coalesce(ipp.worker_classification, 'not_set') = 'employee'
        then 'employee_wage_expense'
      else 'contract_labor_expense'
    end
  ),
  taxable_compensation_amount = case
    when ie.adjustment_type = 'reimbursement' then 0
    when ie.adjustment_type = 'deduction' then 0
    else greatest(coalesce(ie.earning_amount, 0), 0)
  end,
  reimbursement_amount = case
    when ie.adjustment_type = 'reimbursement'
      then greatest(coalesce(ie.earning_amount, 0), 0)
    else 0
  end,
  deduction_amount = case
    when ie.adjustment_type = 'deduction'
      then abs(coalesce(ie.earning_amount, 0))
    else 0
  end
from public.instructor_payroll_profiles ipp
where ipp.studio_id = ie.studio_id
  and ipp.instructor_id = ie.instructor_id
  and (
    ie.worker_classification_snapshot is null
    or ie.accounting_category_snapshot is null
    or (
      ie.taxable_compensation_amount = 0
      and ie.reimbursement_amount = 0
      and ie.deduction_amount = 0
    )
  );

-- -----------------------------------------------------------------------------
-- 5. Append-only compensation activity history
-- -----------------------------------------------------------------------------

create table if not exists public.compensation_activity_history (
  id uuid primary key default gen_random_uuid(),
  studio_id uuid not null references public.studios(id) on delete cascade,
  instructor_id uuid references public.instructors(id) on delete set null,
  earning_id uuid references public.instructor_earnings(id) on delete set null,
  pay_period_id uuid references public.payroll_pay_periods(id) on delete set null,
  payroll_batch_id uuid references public.payroll_batches(id) on delete set null,

  activity_type text not null
    check (
      activity_type in (
        'earning_created',
        'earning_updated',
        'earning_generated',
        'earning_overridden',
        'earning_approved',
        'earning_assigned_to_period',
        'earning_assigned_to_batch',
        'earning_paid',
        'earning_voided',
        'earning_reversed',
        'pay_period_created',
        'pay_period_updated',
        'pay_period_approved',
        'pay_period_paid',
        'pay_period_voided',
        'batch_created',
        'batch_updated',
        'batch_approved',
        'batch_paid',
        'batch_voided',
        'payroll_profile_created',
        'payroll_profile_updated'
      )
    ),

  prior_status text,
  new_status text,
  amount numeric,
  reason text,
  metadata jsonb not null default '{}'::jsonb,

  actor_user_id uuid references public.profiles(id) on delete set null,
  occurred_at timestamptz not null default now()
);

create index if not exists idx_compensation_activity_history_studio_time
  on public.compensation_activity_history (studio_id, occurred_at desc);

create index if not exists idx_compensation_activity_history_earning
  on public.compensation_activity_history (earning_id, occurred_at desc);

create index if not exists idx_compensation_activity_history_batch
  on public.compensation_activity_history (payroll_batch_id, occurred_at desc);

-- -----------------------------------------------------------------------------
-- 6. Updated-at helper
-- -----------------------------------------------------------------------------

create or replace function public.set_payroll_updated_at()
returns trigger
language plpgsql
security invoker
set search_path = public
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists trg_instructor_payroll_profiles_updated_at
  on public.instructor_payroll_profiles;
create trigger trg_instructor_payroll_profiles_updated_at
before update on public.instructor_payroll_profiles
for each row execute function public.set_payroll_updated_at();

drop trigger if exists trg_payroll_pay_periods_updated_at
  on public.payroll_pay_periods;
create trigger trg_payroll_pay_periods_updated_at
before update on public.payroll_pay_periods
for each row execute function public.set_payroll_updated_at();

drop trigger if exists trg_payroll_batches_updated_at
  on public.payroll_batches;
create trigger trg_payroll_batches_updated_at
before update on public.payroll_batches
for each row execute function public.set_payroll_updated_at();

-- -----------------------------------------------------------------------------
-- 7. Automatic append-only activity logging
-- -----------------------------------------------------------------------------

create or replace function public.log_compensation_activity()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  v_activity_type text;
  v_studio_id uuid;
  v_instructor_id uuid;
  v_earning_id uuid;
  v_pay_period_id uuid;
  v_payroll_batch_id uuid;
  v_prior_status text;
  v_new_status text;
  v_amount numeric;
begin
  if tg_table_name = 'instructor_earnings' then
    v_studio_id := new.studio_id;
    v_instructor_id := new.instructor_id;
    v_earning_id := new.id;
    v_pay_period_id := new.pay_period_id;
    v_payroll_batch_id := new.payroll_batch_id;
    v_prior_status := case when tg_op = 'UPDATE' then old.status else null end;
    v_new_status := new.status;
    v_amount := new.earning_amount;

    if tg_op = 'INSERT' then
      v_activity_type := 'earning_created';
    elsif old.status is distinct from new.status then
      v_activity_type := case new.status
        when 'approved' then 'earning_approved'
        when 'paid' then 'earning_paid'
        when 'void' then 'earning_voided'
        else 'earning_updated'
      end;
    elsif old.payroll_batch_id is distinct from new.payroll_batch_id
      and new.payroll_batch_id is not null then
      v_activity_type := 'earning_assigned_to_batch';
    elsif old.pay_period_id is distinct from new.pay_period_id
      and new.pay_period_id is not null then
      v_activity_type := 'earning_assigned_to_period';
    elsif old.pay_mode is distinct from new.pay_mode
      or old.earning_amount is distinct from new.earning_amount then
      v_activity_type := case
        when new.pay_mode = 'manual_override' then 'earning_overridden'
        else 'earning_updated'
      end;
    else
      v_activity_type := 'earning_updated';
    end if;

  elsif tg_table_name = 'payroll_pay_periods' then
    v_studio_id := new.studio_id;
    v_pay_period_id := new.id;
    v_prior_status := case when tg_op = 'UPDATE' then old.status else null end;
    v_new_status := new.status;
    v_amount := new.net_payment_total;

    if tg_op = 'INSERT' then
      v_activity_type := 'pay_period_created';
    elsif old.status is distinct from new.status then
      v_activity_type := case new.status
        when 'approved' then 'pay_period_approved'
        when 'paid' then 'pay_period_paid'
        when 'void' then 'pay_period_voided'
        else 'pay_period_updated'
      end;
    else
      v_activity_type := 'pay_period_updated';
    end if;

  elsif tg_table_name = 'payroll_batches' then
    v_studio_id := new.studio_id;
    v_pay_period_id := new.pay_period_id;
    v_payroll_batch_id := new.id;
    v_prior_status := case when tg_op = 'UPDATE' then old.status else null end;
    v_new_status := new.status;
    v_amount := new.net_payment_total;

    if tg_op = 'INSERT' then
      v_activity_type := 'batch_created';
    elsif old.status is distinct from new.status then
      v_activity_type := case new.status
        when 'approved' then 'batch_approved'
        when 'paid' then 'batch_paid'
        when 'void' then 'batch_voided'
        else 'batch_updated'
      end;
    else
      v_activity_type := 'batch_updated';
    end if;

  elsif tg_table_name = 'instructor_payroll_profiles' then
    v_studio_id := new.studio_id;
    v_instructor_id := new.instructor_id;
    v_activity_type := case
      when tg_op = 'INSERT' then 'payroll_profile_created'
      else 'payroll_profile_updated'
    end;
  end if;

  insert into public.compensation_activity_history (
    studio_id,
    instructor_id,
    earning_id,
    pay_period_id,
    payroll_batch_id,
    activity_type,
    prior_status,
    new_status,
    amount,
    actor_user_id,
    metadata
  )
  values (
    v_studio_id,
    v_instructor_id,
    v_earning_id,
    v_pay_period_id,
    v_payroll_batch_id,
    v_activity_type,
    v_prior_status,
    v_new_status,
    v_amount,
    auth.uid(),
    jsonb_build_object(
      'source_table', tg_table_name,
      'operation', tg_op
    )
  );

  return new;
end;
$$;

drop trigger if exists trg_log_instructor_earnings_activity
  on public.instructor_earnings;
create trigger trg_log_instructor_earnings_activity
after insert or update on public.instructor_earnings
for each row execute function public.log_compensation_activity();

drop trigger if exists trg_log_payroll_pay_period_activity
  on public.payroll_pay_periods;
create trigger trg_log_payroll_pay_period_activity
after insert or update on public.payroll_pay_periods
for each row execute function public.log_compensation_activity();

drop trigger if exists trg_log_payroll_batch_activity
  on public.payroll_batches;
create trigger trg_log_payroll_batch_activity
after insert or update on public.payroll_batches
for each row execute function public.log_compensation_activity();

drop trigger if exists trg_log_instructor_payroll_profile_activity
  on public.instructor_payroll_profiles;
create trigger trg_log_instructor_payroll_profile_activity
after insert or update on public.instructor_payroll_profiles
for each row execute function public.log_compensation_activity();

revoke execute on function public.log_compensation_activity()
  from public, anon, authenticated;
grant execute on function public.log_compensation_activity()
  to service_role;

-- -----------------------------------------------------------------------------
-- 8. Row-level security
-- -----------------------------------------------------------------------------

alter table public.instructor_payroll_profiles enable row level security;
alter table public.payroll_pay_periods enable row level security;
alter table public.payroll_batches enable row level security;
alter table public.compensation_activity_history enable row level security;

-- Sensitive payroll profile access: studio owners/admins only.
drop policy if exists instructor_payroll_profiles_select
  on public.instructor_payroll_profiles;
drop policy if exists instructor_payroll_profiles_insert
  on public.instructor_payroll_profiles;
drop policy if exists instructor_payroll_profiles_update
  on public.instructor_payroll_profiles;
drop policy if exists instructor_payroll_profiles_delete
  on public.instructor_payroll_profiles;

create policy instructor_payroll_profiles_select
on public.instructor_payroll_profiles
for select to authenticated
using (
  exists (
    select 1
    from public.user_studio_roles usr
    where usr.studio_id = instructor_payroll_profiles.studio_id
      and usr.user_id = auth.uid()
      and usr.active = true
      and usr.role in ('studio_owner', 'studio_admin')
  )
);

create policy instructor_payroll_profiles_insert
on public.instructor_payroll_profiles
for insert to authenticated
with check (
  exists (
    select 1
    from public.user_studio_roles usr
    where usr.studio_id = instructor_payroll_profiles.studio_id
      and usr.user_id = auth.uid()
      and usr.active = true
      and usr.role in ('studio_owner', 'studio_admin')
  )
);

create policy instructor_payroll_profiles_update
on public.instructor_payroll_profiles
for update to authenticated
using (
  exists (
    select 1
    from public.user_studio_roles usr
    where usr.studio_id = instructor_payroll_profiles.studio_id
      and usr.user_id = auth.uid()
      and usr.active = true
      and usr.role in ('studio_owner', 'studio_admin')
  )
)
with check (
  exists (
    select 1
    from public.user_studio_roles usr
    where usr.studio_id = instructor_payroll_profiles.studio_id
      and usr.user_id = auth.uid()
      and usr.active = true
      and usr.role in ('studio_owner', 'studio_admin')
  )
);

-- Pay periods: owners/admins prepare; only owners may set paid/void.
drop policy if exists payroll_pay_periods_select
  on public.payroll_pay_periods;
drop policy if exists payroll_pay_periods_insert
  on public.payroll_pay_periods;
drop policy if exists payroll_pay_periods_update
  on public.payroll_pay_periods;
drop policy if exists payroll_pay_periods_delete
  on public.payroll_pay_periods;

create policy payroll_pay_periods_select
on public.payroll_pay_periods
for select to authenticated
using (
  exists (
    select 1
    from public.user_studio_roles usr
    where usr.studio_id = payroll_pay_periods.studio_id
      and usr.user_id = auth.uid()
      and usr.active = true
      and usr.role in ('studio_owner', 'studio_admin')
  )
);

create policy payroll_pay_periods_insert
on public.payroll_pay_periods
for insert to authenticated
with check (
  exists (
    select 1
    from public.user_studio_roles usr
    where usr.studio_id = payroll_pay_periods.studio_id
      and usr.user_id = auth.uid()
      and usr.active = true
      and usr.role in ('studio_owner', 'studio_admin')
  )
  and payroll_pay_periods.status in ('open', 'in_review', 'approved')
);

create policy payroll_pay_periods_update
on public.payroll_pay_periods
for update to authenticated
using (
  exists (
    select 1
    from public.user_studio_roles usr
    where usr.studio_id = payroll_pay_periods.studio_id
      and usr.user_id = auth.uid()
      and usr.active = true
      and usr.role in ('studio_owner', 'studio_admin')
  )
)
with check (
  exists (
    select 1
    from public.user_studio_roles usr
    where usr.studio_id = payroll_pay_periods.studio_id
      and usr.user_id = auth.uid()
      and usr.active = true
      and (
        usr.role = 'studio_owner'
        or (
          usr.role = 'studio_admin'
          and payroll_pay_periods.status in ('open', 'in_review', 'approved')
        )
      )
  )
);

-- Payroll batches: owners/admins prepare; only owners may set paid/void.
drop policy if exists payroll_batches_select
  on public.payroll_batches;
drop policy if exists payroll_batches_insert
  on public.payroll_batches;
drop policy if exists payroll_batches_update
  on public.payroll_batches;
drop policy if exists payroll_batches_delete
  on public.payroll_batches;

create policy payroll_batches_select
on public.payroll_batches
for select to authenticated
using (
  exists (
    select 1
    from public.user_studio_roles usr
    where usr.studio_id = payroll_batches.studio_id
      and usr.user_id = auth.uid()
      and usr.active = true
      and usr.role in ('studio_owner', 'studio_admin')
  )
);

create policy payroll_batches_insert
on public.payroll_batches
for insert to authenticated
with check (
  exists (
    select 1
    from public.user_studio_roles usr
    where usr.studio_id = payroll_batches.studio_id
      and usr.user_id = auth.uid()
      and usr.active = true
      and usr.role in ('studio_owner', 'studio_admin')
  )
  and payroll_batches.status in ('draft', 'in_review', 'approved')
);

create policy payroll_batches_update
on public.payroll_batches
for update to authenticated
using (
  exists (
    select 1
    from public.user_studio_roles usr
    where usr.studio_id = payroll_batches.studio_id
      and usr.user_id = auth.uid()
      and usr.active = true
      and usr.role in ('studio_owner', 'studio_admin')
  )
)
with check (
  exists (
    select 1
    from public.user_studio_roles usr
    where usr.studio_id = payroll_batches.studio_id
      and usr.user_id = auth.uid()
      and usr.active = true
      and (
        usr.role = 'studio_owner'
        or (
          usr.role = 'studio_admin'
          and payroll_batches.status in ('draft', 'in_review', 'approved')
        )
      )
  )
);

-- Append-only activity history.
drop policy if exists compensation_activity_history_select
  on public.compensation_activity_history;
drop policy if exists compensation_activity_history_insert
  on public.compensation_activity_history;
drop policy if exists compensation_activity_history_update
  on public.compensation_activity_history;
drop policy if exists compensation_activity_history_delete
  on public.compensation_activity_history;

create policy compensation_activity_history_select
on public.compensation_activity_history
for select to authenticated
using (
  exists (
    select 1
    from public.user_studio_roles usr
    where usr.studio_id = compensation_activity_history.studio_id
      and usr.user_id = auth.uid()
      and usr.active = true
      and usr.role in ('studio_owner', 'studio_admin')
  )
);

-- Tighten legacy compensation-table access.
drop policy if exists instructor_compensation_rules_select
  on public.instructor_compensation_rules;
drop policy if exists instructor_compensation_rules_insert
  on public.instructor_compensation_rules;
drop policy if exists instructor_compensation_rules_update
  on public.instructor_compensation_rules;
drop policy if exists instructor_compensation_rules_delete
  on public.instructor_compensation_rules;

create policy instructor_compensation_rules_select
on public.instructor_compensation_rules
for select to authenticated
using (
  exists (
    select 1
    from public.user_studio_roles usr
    where usr.studio_id = instructor_compensation_rules.studio_id
      and usr.user_id = auth.uid()
      and usr.active = true
      and usr.role in ('studio_owner', 'studio_admin')
  )
);

create policy instructor_compensation_rules_insert
on public.instructor_compensation_rules
for insert to authenticated
with check (
  exists (
    select 1
    from public.user_studio_roles usr
    where usr.studio_id = instructor_compensation_rules.studio_id
      and usr.user_id = auth.uid()
      and usr.active = true
      and usr.role in ('studio_owner', 'studio_admin')
  )
);

create policy instructor_compensation_rules_update
on public.instructor_compensation_rules
for update to authenticated
using (
  exists (
    select 1
    from public.user_studio_roles usr
    where usr.studio_id = instructor_compensation_rules.studio_id
      and usr.user_id = auth.uid()
      and usr.active = true
      and usr.role in ('studio_owner', 'studio_admin')
  )
)
with check (
  exists (
    select 1
    from public.user_studio_roles usr
    where usr.studio_id = instructor_compensation_rules.studio_id
      and usr.user_id = auth.uid()
      and usr.active = true
      and usr.role in ('studio_owner', 'studio_admin')
  )
);

drop policy if exists instructor_earnings_select
  on public.instructor_earnings;
drop policy if exists instructor_earnings_insert
  on public.instructor_earnings;
drop policy if exists instructor_earnings_update
  on public.instructor_earnings;
drop policy if exists instructor_earnings_delete
  on public.instructor_earnings;

create policy instructor_earnings_select
on public.instructor_earnings
for select to authenticated
using (
  exists (
    select 1
    from public.user_studio_roles usr
    where usr.studio_id = instructor_earnings.studio_id
      and usr.user_id = auth.uid()
      and usr.active = true
      and usr.role in ('studio_owner', 'studio_admin')
  )
);

create policy instructor_earnings_insert
on public.instructor_earnings
for insert to authenticated
with check (
  exists (
    select 1
    from public.user_studio_roles usr
    where usr.studio_id = instructor_earnings.studio_id
      and usr.user_id = auth.uid()
      and usr.active = true
      and usr.role in ('studio_owner', 'studio_admin')
  )
  and instructor_earnings.status in ('pending', 'approved')
);

create policy instructor_earnings_update
on public.instructor_earnings
for update to authenticated
using (
  exists (
    select 1
    from public.user_studio_roles usr
    where usr.studio_id = instructor_earnings.studio_id
      and usr.user_id = auth.uid()
      and usr.active = true
      and usr.role in ('studio_owner', 'studio_admin')
  )
)
with check (
  exists (
    select 1
    from public.user_studio_roles usr
    where usr.studio_id = instructor_earnings.studio_id
      and usr.user_id = auth.uid()
      and usr.active = true
      and (
        usr.role = 'studio_owner'
        or (
          usr.role = 'studio_admin'
          and instructor_earnings.status in ('pending', 'approved')
        )
      )
  )
);

-- No DELETE policies are recreated for payroll-sensitive tables.

commit;
